### ISSUE TITLE
Does this work for scanned pdfs?

### ISSUE THREAD

**Issue by ajithvcoder** [pdftables/python-pdftables-api#10]
its working for pdf files that are typed pdf but for scanned pdf output excel file is corrupted.

**Comment by StevenMaude** [comment]
Hi!

PDFTables.com  [doesn't currently](https://pdftables.com/faq#ocr) extract scanned documents; however, as the linked page mentions, you can try running your PDF through OCR software first and then submitting it to PDFTables.com.

Hope that helps 🙂

**Comment by ajithvcoder** [comment]
Thanks will try that method
