### ISSUE TITLE
My-api-key

### ISSUE THREAD

**Issue by anandhkirupa** [pdftables/python-pdftables-api#19]
![doubt](https://user-images.githubusercontent.com/33204634/66207915-9bec0380-e6d1-11e9-8693-c6f2833ca96d.png)

Please explain what is "my-api-key"? Do we need mention anything key?

If so what is that??

**Comment by StevenMaude** [comment]
Hi @anandhkirupa, we've updated the README to explain it more fully.

`my-api-key` is an API key that you get when you create an account at PDFTables.com and then visit the [API page](https://pdftables.com/pdf-to-excel-api) while logged in.
