### ISSUE TITLE
TypeError: a float is required

### ISSUE THREAD

**Issue by julianyraiol** [pdftables/python-pdftables-api#9]
Hello, I'm trying convert a pdf to csv file, but when I call the script, show  this error .

**Comment by StevenMaude** [comment]
Hi @julianyraiol; could you paste the full output of the error here, please to help us debug the problem for you?

That is, everything from:

```
Traceback (most recent call last):
```

to the actual `TypeError` message.

Thanks!

**Comment by StevenMaude** [comment]
Closing as we've had no more details on this; feel free to add some more information for us to debug and we can reopen this :slightly_smiling_face:
